services:
  nestJs :
    image: mcr.microsoft.com/devcontainers/typescript-node
    volumes:
      - ..:/workspace:cached
    ports:
      - "3000:3000"
      - "5173:5173"
    # environment:
    #   - NODE_ENV=development
    #   - PORT=3000
    command: sleep infinity
