services:
  nestJs :
    image: mcr.microsoft.com/devcontainers/typescript-node
    volumes:
      - ..:/workspace:cached
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: sleep infinity
